package tui

const (
	flagDir     = "--dir"
	flagScope   = "--scope"
	flagTSV     = "--tsv"
	flagProject = "--project"
	flagVerbose = "--verbose"
	flagName    = "--name"
	flagTarget  = "--target"

	commandAdd       = "add"
	commandRemove    = "remove"
	commandRename    = "rename"
	commandUninstall = "uninstall"
	commandUpdate    = "update"

	labelCodex       = "Codex"
	labelClaude      = "Claude"
	labelGemini      = "Gemini"
	labelAntigravity = "Antigravity"
	labelTargets     = "Targets"

	statusLoadingInstalled = "Loading installed skills..."
	statusEnterSource      = "Enter a source path or git URL."
	statusNoInstalledSkill = "No installed skill selected."
	statusNoSourceSelected = "No source selected."
	statusSyncing          = "Syncing sources..."
	statusReturnedSkills   = "Returned to skills."
	statusSelectTarget     = "Select at least one supported install target."

	keyEsc       = "esc"
	keyEnter     = "enter"
	keyBackspace = "backspace"
	keyDown      = "down"

	scopeGlobal           = "global"
	scopeProject          = "project"
	scopeCustom           = "custom"
	managedYes            = "yes"
	targetCodex           = "codex"
	targetClaude          = "claude"
	targetDirectory       = "directory"
	targetGemini          = "gemini"
	targetAntigravity     = "antigravity"
	targetOpenCode        = "opencode"
	targetPurposeInstall  = "install"
	targetStatusSupported = "supported"
	targetAdapterSkillDir = "skill-dir"
	targetGroupCustomDirs = "Custom directories"
	targetGroupProjects   = "Projects"
	queueStateDone        = "done"
	queueStateFailed      = "failed"
	queueStatePending     = "pending"
	queueStateRunning     = "running"
	uiSelectedCursor      = "›"

	actionRemoveSource = "Remove source"
	actionRenameSource = "Rename source"
)
